---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: opcua-server-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: opcua-server
  template:
    metadata:
      labels:
        app: opcua-server
    spec:
      containers:
        - name: opcua-server
          image: litmus/opcua_server
          ports:
            - containerPort: 4840

---
apiVersion: v1
kind: Service
metadata:
  name: opcua-server-service
spec:
  type: NodePort
  selector:
    app: opcua-server
  ports:
    - port: 4840
      targetPort: 4840
      protocol: TCP