---
nats:
  nats_address: nats://10.30.50.1:4222
  nats_client_name: L1_Machine1
  request_topics:
    - simulation.settings.l1_m1
simulation_settings:
  Uptime_Base: 300
  Uptime_Variation_Factor: 0.2
  Downtime_Base: 60
  Downtime_Variation_Factor: 0.5
  CycleTime_Base: 30
  CycleTime_Variation_Factor: 0.25
  TaktTime_Base: 10
  TakeTime_Variation_Factor: 0.5
  FaultOccurrence_Factor: 0.73
  FaultCode_Min_Value: 1
  FaultCode_Max_Value: 4
  FaultCode_L2_Min_Value: 1
  FaultCode_L2_Max_Value: 6
  ReasonCode_Min: 1
  ReasonCode_Max: 10
  ReasonCode_L2_Min: 1
  ReasonCode_L2_Max: 10
  QualityCode_Scrap_Min: 2
  QualityCode_Scrap_Max: 6
  BadPartInterval_Base: 4
  BadPartInterval_Variation: 2
  Temperature_LowerControlLimit: 15
  Temperature_UpperControlLimit: 25
