---
nats:
  nats_address: nats://10.30.50.1:4222
  nats_client_name: L1_Machine1
  request_topics:
    - simulation.settings.l1_m1
simulation_settings:
  Uptime_Base: 3000
  Uptime_Variation_Factor: 0.1
  Downtime_Base: 60
  Downtime_Variation_Factor: 0.5
  CycleTime_Base: 30
  CycleTime_Variation_Factor: 0.1
  TaktTime_Base: 1
  TakeTime_Variation_Factor: 0.1
  FaultOccurrence_Factor: 0.73
  FaultCode_Min_Value: 1
  FaultCode_Max_Value: 4
  FaultCode_L2_Min_Value: 1
  FaultCode_L2_Max_Value: 6
  ReasonCode_Min: 1
  ReasonCode_Max: 10
  ReasonCode_L2_Min: 1
  ReasonCode_L2_Max: 10
  QualityCode_Scrap_Min: 2
  QualityCode_Scrap_Max: 6
  BadPartInterval_Base: 100
  BadPartInterval_Variation: 1
  Temperature_LowerControlLimit: 15
  Temperature_UpperControlLimit: 25
  ReasonCodes:
    - rc: 1
      desc: Material
      prob: 0.2
      l2:
        - rc: 1
          desc: Lack of material
          prob: 0.2
        - rc: 2
          desc: Wrong material
          prob: 0.1
        - rc: 3
          desc: Return material
          prob: 0.1
        - rc: 4
          desc: Quality issue
          prob: 0.4
        - rc: 5
          desc: Reload
          prob: 0.2
    - rc: 2
      desc: Staffing
      prob: 0.1
      l2:
        - rc: 1
          desc: Break
          prob: 0.2
        - rc: 2
          desc: Lunch
          prob: 0.1
        - rc: 3
          desc: No Operator
          prob: 0.1
        - rc: 4
          desc: Quality issue
          prob: 0.4
        - rc: 5
          desc: Reload
          prob: 0.2
